/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphingcalculator;

/**
 *
 * @author pikes7641
 */
public class GraphingCalculatorInterface extends javax.swing.JFrame {

    /**
     * Creates new form GraphingCalculatorInterface
     */
    public GraphingCalculatorInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PolynomialButton = new javax.swing.JButton();
        ExponentialButton = new javax.swing.JButton();
        RationalButton = new javax.swing.JButton();
        LogarithmicButton = new javax.swing.JButton();
        SineButton = new javax.swing.JButton();
        CosineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PolynomialButton.setText("Polynomial");
        PolynomialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolynomialButtonActionPerformed(evt);
            }
        });

        ExponentialButton.setText("Exponential");
        ExponentialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponentialButtonActionPerformed(evt);
            }
        });

        RationalButton.setText("Rational");
        RationalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RationalButtonActionPerformed(evt);
            }
        });

        LogarithmicButton.setText("Logarithmic");
        LogarithmicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarithmicButtonActionPerformed(evt);
            }
        });

        SineButton.setText("Sine");
        SineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SineButtonActionPerformed(evt);
            }
        });

        CosineButton.setText("Cosine");
        CosineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PolynomialButton)
                        .addGap(18, 18, 18)
                        .addComponent(ExponentialButton)
                        .addGap(18, 18, 18)
                        .addComponent(RationalButton)
                        .addGap(18, 18, 18)
                        .addComponent(LogarithmicButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SineButton)
                        .addGap(18, 18, 18)
                        .addComponent(CosineButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PolynomialButton)
                    .addComponent(ExponentialButton)
                    .addComponent(RationalButton)
                    .addComponent(LogarithmicButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SineButton)
                    .addComponent(CosineButton))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PolynomialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolynomialButtonActionPerformed
        PolynomialInterface PolynomialPanel = new PolynomialInterface();
        PolynomialPanel.setVisible(true);
    }//GEN-LAST:event_PolynomialButtonActionPerformed

    private void ExponentialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExponentialButtonActionPerformed
        ExponentialInterface ExponentialPanel = new ExponentialInterface();
        ExponentialPanel.setVisible(true);
    }//GEN-LAST:event_ExponentialButtonActionPerformed

    private void SineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SineButtonActionPerformed
        SineInterface SinePanel = new SineInterface();
        SinePanel.setVisible(true);
    }//GEN-LAST:event_SineButtonActionPerformed

    private void CosineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosineButtonActionPerformed
        CosineInterface CosinePanel = new CosineInterface();
        CosinePanel.setVisible(true);
    }//GEN-LAST:event_CosineButtonActionPerformed

    private void LogarithmicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarithmicButtonActionPerformed
        LogarithmicInterface LogarithmicPanel = new LogarithmicInterface();
        LogarithmicPanel.setVisible(true);
    }//GEN-LAST:event_LogarithmicButtonActionPerformed

    private void RationalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RationalButtonActionPerformed
        RationalInterface RationalPanel = new RationalInterface();
        RationalPanel.setVisible(true);
    }//GEN-LAST:event_RationalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphingCalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphingCalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphingCalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphingCalculatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphingCalculatorInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CosineButton;
    private javax.swing.JButton ExponentialButton;
    private javax.swing.JButton LogarithmicButton;
    private javax.swing.JButton PolynomialButton;
    private javax.swing.JButton RationalButton;
    private javax.swing.JButton SineButton;
    // End of variables declaration//GEN-END:variables
}
